[phases.setup]
aptPkgs = [
  "chromium",
  "libglib2.0-0",
  "libgobject-2.0-0",
  "libnss3",
  "libatk1.0-0",
  "libatk-bridge2.0-0",
  "libcups2",
  "libdbus-1-3",
  "libxkbcommon0",
  "libxshmfence1",
  "libasound2t64",
  "libpangocairo-1.0-0",
  "libpango-1.0-0",
  "libxss1",
  "libgtk-3-0",
  "libgbm1",
  "libglu1",
  "fonts-liberation",
  "xdg-utils",
  "wget",
  "ca-certificates"
]