[build]
  builder = "nixpacks"

[deploy]
  restartPolicyType = "always"
  healthcheckPath = "/health"
  healthcheckTimeout = 300

[env]
  NODE_ENV = "production"
  CORS_ORIGINS = "http://localhost:5174,https://balagh-admin.vercel.app"
  CHROME_BIN = "/usr/bin/chromium"