[build]
  builder = "nixpacks"

[deploy]
  restartPolicyType = "always"
  healthcheckPath = "/health"
  healthcheckTimeout = 300

[env]
NODE_ENV = "production"
CORS_ORIGINS = "http://localhost:5174,https://balagh-admin.vercel.app"
PUPPETEER_EXECUTABLE_PATH = "/usr/bin/chromium"
